### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by yzcv** [bearshng/mvntf#1]
I have tried to run your code, but it cannot work.  The error is as follows.
>> testMVNTF
引用了不存在的字段 'convergeNum'。

出错 mvntf (line 12)
convergeNum=options.convergeNum;%converge number

出错 testMVNTF (line 15)
t=mvntf(tensorData,EndNum,rankNumber,btdInit{1},btdInit{2},btdInit{3},options);

**Comment by yzcv** [comment]
I wonder to know what should I do next? Thanks!

**Comment by bearshng** [comment]
@z625715875   I am sorry for this error. I forgot to set the convergence number. This issue has fixed in testMVNTF.m. Please refer to  the  latest code.
